# Certificate

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-prod
spec:
  secretName: letsencrypt-prod
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "*.hh.pair.sharing.io"
  dnsNames:
    - hh.pair.sharing.io
    - "*.hh.pair.sharing.io"
