# Cluster-Issuer

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: dns@ii.coop
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - dns01:
        rfc2136:
          tsigKeyName: pair
          tsigAlgorithm: HMACMD5
          tsigSecretSecretRef:
            name: tsig-powerdns
            key: powerdns
          nameserver: 139.178.68.188
      selector:
        dnsNames:
          - "*.hh.pair.sharing.io"
          - "hh.pair.sharing.io"
