

# #+NAME: Certs

# Source: sharingio-pair/templates/cert.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pair-dev-sharingio-pair-letsencrypt
spec:
  secretName: pair-dev-sharingio-pair-letsencrypt
  issuerRef:
    name: pair-dev-sharingio-pair-letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - "pair-dev.sharing.io"
---
# Source: sharingio-pair/templates/cluster-issuer.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: pair-dev-sharingio-pair-letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: sharingio@ii.coop
    privateKeySecretRef:
      name: pair-dev-sharingio-pair-letsencrypt
    solvers:
      - http01:
          ingress:
            class: nginx
        selector:
          dnsNames:
            - "pair-dev.sharing.io"
