

# #+NAME: Ingress

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pair-dev-sharing-io
spec:
  rules:
  - host: pair-dev.sharing.io
    http:
      paths:
      - backend:
          serviceName: humacs
          servicePort: 5000
        path: /
  tls:
  - hosts:
    - pair-dev.sharing.io
    secretName: pair-dev-sharingio-pair-letsencrypt
