# Configure

apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  releaseName: metrics-server
  chart:
    repository: https://charts.helm.sh/stable
    name: metrics-server
    version: 2.11.2
  values:
    args:
      - --logtostderr
      - --kubelet-preferred-address-types=InternalIP
      - --kubelet-insecure-tls
