apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: sharingio-pair
spec:
  releaseName: sharingio-pair
  chart:
    git: https://github.com/sharingio/pair.git
    ref: ${SHARINGIO_PAIR_TAG}
    path: charts/sharingio-pair
  values:
    permittedOrgs:
      - sharingio
      - cncf
      - kubernetes
      - ii
    adminEmailDomain: ii.coop
    instance:
      kubernetesVersion: 1.21.2
      humacsRepository: registry.gitlab.com/humacs/humacs/ii
      humacsVersion: 2021.08.30.2307
      nodeSize: c3.small.x86
    sessionSecret: pairpairpairpair
    githubOAuth:
      id: ${SHARINGIO_PAIR_GITHUB_OAUTH_ID}
      secret: ${SHARINGIO_PAIR_GITHUB_OAUTH_SECRET}
    equinixMetal:
      projectID: ${SHARINGIO_PAIR_EQUINIX_METAL_PROJECT_ID}
    client:
      image:
        tag: ${SHARINGIO_PAIR_TAG}
      autoscaling:
        enabled: true
        minReplicas: 3
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - client
                topologyKey: "kubernetes.io/hostname"
      resources:
        requests:
          cpu: 50m
          memory: 400Mi
    clusterapimanager:
      image:
        tag: ${SHARINGIO_PAIR_TAG}
      autoscaling:
        enabled: true
        minReplicas: 9
      resources:
        requests:
          cpu: 60m
          memory: 70Mi
        limits:
          cpu: 60m
          memory: 70Mi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - clusterapimanager
                topologyKey: "kubernetes.io/hostname"
    ingress:
      enabled: true
      certmanager:
        enabled: true
      hosts:
        - host: ${SHARINGIO_PAIR_HOST}
          paths:
            - /
