apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: sharingio-pair
spec:
  releaseName: sharingio-pair
  chart:
    git: https://github.com/sharingio/pair.git
    ref: ${SHARINGIO_PAIR_TAG}
    path: charts/sharingio-pair
  values:
    permittedOrgs:
      - "*"
    adminEmailDomain: ii.coop
    instance:
      kubernetesVersion: 1.23.5
      environmentRepository: registry.gitlab.com/sharingio/environment/environment
      environmentVersion: 2022.03.30.1618
      nodeSize: n2.xlarge.x86
    sessionSecret: pairpairpairpair
    maxInstancesForNonAdmins: 1
    githubOAuth:
      id: ${SHARINGIO_PAIR_GITHUB_OAUTH_ID}
      secret: ${SHARINGIO_PAIR_GITHUB_OAUTH_SECRET}
    equinixMetal:
      projectID: ${SHARINGIO_PAIR_EQUINIX_METAL_PROJECT_ID}
    client:
      image:
        tag: ${SHARINGIO_PAIR_TAG}
      autoscaling:
        enabled: true
        minReplicas: 2
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - client
                topologyKey: "kubernetes.io/hostname"
      resources:
        requests:
          cpu: 200m
          memory: 400Mi
    clusterapimanager:
      image:
        tag: ${SHARINGIO_PAIR_TAG}
      autoscaling:
        enabled: true
        minReplicas: 2
      resources:
        requests:
          cpu: 200m
          memory: 70Mi
        limits:
          cpu: 200m
          memory: 70Mi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - clusterapimanager
                topologyKey: "kubernetes.io/hostname"
    reconciler:
      image:
        tag: ${SHARINGIO_PAIR_TAG}
    ingress:
      enabled: true
      certmanager:
        enabled: true
      hosts:
        - host: ${SHARINGIO_PAIR_HOST}
          paths:
            - /
    registry:
      enabled: true
      ingress:
        enabled: true
        certmanager:
          enabled: true
          domainSuffix: -docker-mirror.sharing.io
