apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: sharingio-pair
spec:
  releaseName: sharingio-pair
  chart:
    git: https://github.com/sharingio/pair.git
    ref: ${SHARINGIO_PAIR_TAG}
    path: charts/sharingio-pair
  values:
    permittedOrgs:
      - sharingio
      - cncf
      - kubernetes
    adminEmailDomain: ii.coop
    instance:
      kubernetesVersion: 1.21.2
      humacsRepository: registry.gitlab.com/humacs/humacs/ii
      humacsVersion: 2021.06.28.2240
    sessionSecret: pairpairpairpair
    githubOAuth:
      id: ${SHARINGIO_PAIR_GITHUB_OAUTH_ID}
      secret: ${SHARINGIO_PAIR_GITHUB_OAUTH_SECRET}
    equinixMetal:
      projectID: ${SHARINGIO_PAIR_EQUINIX_METAL_PROJECT_ID}
    client:
      image:
        tag: ${SHARINGIO_PAIR_TAG}
      resources:
        requests:
          cpu: 50m
          memory: 400Mi
    clusterapimanager:
      image:
        tag: ${SHARINGIO_PAIR_TAG}
      autoscaling:
        enabled: true
        minReplicas: 2
      resources:
        requests:
          cpu: 60m
          memory: 70Mi
        limits:
          cpu: 60m
          memory: 70Mi
    ingress:
      enabled: true
      certmanager:
        enabled: true
      hosts:
        - host: ${SHARINGIO_PAIR_HOST}
          paths:
            - /
