#ci-sa:noapply=true
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sharingio-pair-ci
  namespace: sharingio-pair
rules:
- apiGroups:
  - 'helm.fluxcd.io'
  resources:
  - 'helmreleases'
  verbs:
  - update
  - patch
