#ci-sa:noapply=true
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sharingio-pair-ci
  namespace: sharingio-pair
rules:
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
      - update
      - patch
      - create
  - apiGroups:
      - helm.fluxcd.io
    resources:
      - helmreleases
    verbs:
      - get
      - list
      - update
      - patch
      - create
