{{- if .Values.ingress.enabled }}
{{- if .Values.ingress.certmanager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "sharingio-pair.fullname" . }}-letsencrypt
  labels:
    app.kubernetes.io/part-of: sharingio-pair
    {{- include "sharingio-pair.labels" . | nindent 4 }}
spec:
  secretName: {{ include "sharingio-pair.fullname" . }}-letsencrypt
  issuerRef:
    name: {{ include "sharingio-pair.fullname" . }}-letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    {{- range .Values.ingress.hosts }}
    - {{ .host | quote }}
    {{- end }}
{{- end }}
{{- end }}
