{{- if .Values.ingress.enabled }}
{{- if .Values.ingress.certmanager.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ include "sharingio-pair.fullname" . }}-letsencrypt
  labels:
    app.kubernetes.io/part-of: sharingio-pair
    {{- include "sharingio-pair.labels" . | nindent 4 }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.ingress.certmanager.email | default "sharingio@ii.coop" }}
    privateKeySecretRef:
      name: {{ include "sharingio-pair.fullname" . }}-letsencrypt
    solvers:
      - http01:
          ingress:
            class: nginx
        selector:
          dnsNames:
            {{- range .Values.ingress.hosts }}
            - {{ .host | quote }}
            {{- end }}
            {{- if .Values.registry.enabled }}
            {{- if .Values.registry.ingress.certmanager.enabled }}
            {{ range .Values.registry.mirrors }}
            - "{{ .name }}{{ $.Values.registry.ingress.domainSuffix }}"
            {{- end }}
            {{- end }}
            {{- end }}
{{- end }}
{{- end }}
