{{- if .Values.registry.enabled }}
{{ $fullname := include "sharingio-pair.fullname" . }}
{{ $labels := include "sharingio-pair.labels" . }}
{{ $selectorLabels := include "sharingio-pair.selectorLabels" . }}
{{ range $.Values.registry.mirrors }}
{{ $registryName := .name }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullname }}-registry-{{ .name }}
  labels:
    app: registry
    app.kubernetes.io/part-of: sharingio-pair
    {{- $labels | nindent 4 }}
data:
  config.yml: |
    version: 0.1
    log:
      fields:
        service: registry
    storage:
      cache:
        blobdescriptor: inmemory
      filesystem:
        rootdirectory: /var/lib/registry
    http:
      addr: :5000
      headers:
        X-Content-Type-Options: [nosniff]
        Registry-Mirrors-From: [{{ .name }}]
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3
    proxy:
      remoteurl: {{ .url }}
{{ printf "---" }}
{{- end }}
{{- end }}
