{{- if .Values.registry.enabled -}}
{{- $svcPort := .Values.registry.service.port -}}
{{ $fullname := include "sharingio-pair.fullname" . }}
{{ $labels := include "sharingio-pair.labels" . }}
{{ $selectorLabels := include "sharingio-pair.selectorLabels" . }}
{{ range $.Values.registry.mirrors }}
{{ $registryName := .name }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullname }}-registry-{{ $registryName }}
  labels:
    {{- $labels | nindent 4 }}
  {{- with $.Values.registry.ingress.annotations }}
  annotations:
    {{- if $.Values.registry.ingress.certmanager.enabled }}
    cert-manager.io/cluster-issuer: {{ $fullname }}-letsencrypt
    {{- end }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if $.Values.registry.ingress.certmanager }}
  tls:
    - hosts:
    {{- range $.Values.registry.ingress.hosts }}
        - {{ .host | quote }}
    {{- end }}
      secretName: {{ $fullname }}-letsencrypt
  {{- else if $.Values.registry.ingress.tls }}
  tls:
    {{- range $.Values.registry.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: "{{ .name }}{{ $.Values.registry.ingress.domainSuffix }}"
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullname }}-registry-{{ $registryName }}
                port:
                  number: {{ $svcPort }}
{{ printf "---" }}
  {{- end }}
{{- end }}
