{{- if .Values.clusterapimanager.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "sharingio-pair.fullname" . }}-clusterapimanager
  labels:
    app: clusterapimanager
    app.kubernetes.io/part-of: sharingio-pair
    {{- include "sharingio-pair.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - "controlplane.cluster.x-k8s.io"
    resources:
      - kubeadmcontrolplanes
    verbs:
      - create
      - get
      - list
      - delete
  - apiGroups:
      - "infrastructure.cluster.x-k8s.io"
    resources:
      - packetmachinetemplates
      - packetclusters
      - packetmachines
    verbs:
      - create
      - get
      - list
      - delete
  - apiGroups:
      - "infrastructure.cluster.x-k8s.io"
    resources:
      - packetmachines
    verbs:
      - deletecollection
  - apiGroups:
      - "cluster.x-k8s.io"
    resources:
      - clusters
      - machinedeployments
      - machines
    verbs:
      - create
      - get
      - list
      - delete
      - deletecollection
      - list
  - apiGroups:
      - "bootstrap.cluster.x-k8s.io"
    resources:
      - kubeadmconfigtemplates
    verbs:
      - create
      - get
      - list
      - delete
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
  - apiGroups:
      - externaldns.k8s.io
    resources:
      - dnsendpoints
    verbs:
      - get
      - create
      - update
      - deletecollection
{{- end }}
