{{- if .Values.clusterapimanager.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "sharingio-pair.fullname" . }}-clusterapimanager
  labels:
    app: clusterapimanager
    app.kubernetes.io/part-of: sharingio-pair
    {{- include "sharingio-pair.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "sharingio-pair.fullname" . }}-clusterapimanager
subjects:
- kind: ServiceAccount
  name: {{ include "sharingio-pair.fullname" . }}-clusterapimanager
  namespace: {{ .Release.Namespace }}
{{- end }}
