apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sharingio-pair.fullname" . }}
  labels:
    app.kubernetes.io/part-of: sharingio-pair
    {{- include "sharingio-pair.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.sessionSecret }}
  sessionSecret: {{ .Values.sessionSecret | toString | b64enc }}
  {{- end }}
  {{- if .Values.githubOAuth.id }}
  githubOAuthID: {{ .Values.githubOAuth.id | toString | b64enc }}
  {{- end }}
  {{- if .Values.githubOAuth.secret }}
  githubOAuthSecret: {{ .Values.githubOAuth.secret | toString | b64enc }}
  {{- end }}
  {{- if .Values.equinixMetal.projectID }}
  equinixMetalProjectID: {{ .Values.equinixMetal.projectID | toString | b64enc }}
  {{- end }}
