{{- if .Values.registry.enabled }}
{{ $fullname := include "sharingio-pair.fullname" . }}
{{ $labels := include "sharingio-pair.labels" . }}
{{ $selectorLabels := include "sharingio-pair.selectorLabels" . }}
{{ range $.Values.registry.mirrors }}
{{ $registryName := .name }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}-registry-{{ .name }}
  labels:
    app: registry
    app.kubernetes.io/part-of: sharingio-pair
    {{- $labels | nindent 4 }}
spec:
  type: {{ $.Values.registry.service.type }}
  ports:
    - port: {{ $.Values.registry.service.port }}
      targetPort: {{ $.Values.registry.service.port }}
      protocol: TCP
      name: http
  selector:
    app: registry
    mirroring: {{ .url }}
    app.kubernetes.io/part-of: sharingio-pair
    {{- $selectorLabels | nindent 4 }}
{{ printf "---" }}
{{- end}}
{{- end}}
