{{- if .Values.registry.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sharingio-pair.fullname" . }}-registry
  labels:
    app: registry
    app.kubernetes.io/part-of: sharingio-pair
    {{- include "sharingio-pair.labels" . | nindent 4 }}
spec:
  type: {{ .Values.registry.service.type }}
  ports:
    - port: {{ .Values.registry.service.port }}
      targetPort: {{ .Values.registry.service.port }}
      protocol: TCP
      name: http
  selector:
    app: registry
    app.kubernetes.io/part-of: sharingio-pair
    {{- include "sharingio-pair.selectorLabels" . | nindent 4 }}
{{- end}}
