{{- if .Values.clusterapimanager.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sharingio-pair.fullname" . }}-clusterapimanager
  labels:
    app: clusterapimanager
    app.kubernetes.io/part-of: sharingio-pair
    {{- include "sharingio-pair.labels" . | nindent 4 }}
  {{- with .Values.clusterapimanager.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
